[package]
name = "discrete-gaussian"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
rustdoc-args = ["--document-private-items", "--extern-html-root-url=https://docs.rs/"]
readme = "README.md"

[lib]

[dependencies]
rand = "0.8.5"
scalarff = "0.4.3"